### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by jgcazares92** [jlwoolf/pyscape#1]
Hey there. Found this project on SO when searching for a way to convert SVG to png. I really like how straightforward the instructions are. However, I'm receiving the following error when I try to export an SVG in png format:

Traceback (most recent call last):
  File "convert_svg_png.py", line 7, in <module>
    img = svg.export(stem='out/file', format="png", dpi=1200)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscape\SVG.py", line 379, in export
    img = self.im(dpi, size, margin, area, filter, renderer=renderer)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscape\SVG.py", line 347, in im
    return self.__im(dpi, size, margin, area)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscape\SVG.py", line 242, in __im
    return self.__im_skia(dpi, size)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscape\SVG.py", line 175, in __im_skia
    surface = skia.Surface(round(sw), round(sh))
TypeError: pybind11::init(): factory function returned nullptr

And here is my code:
```
from pyscape import SVG

svg = SVG('Plots/SimPlots/plot1.svg')
img = svg.export(stem='out/file', format="png", dpi=1200)
```

**Comment by jlwoolf** [comment]
Sorry I didn't get back to you sooner. I have made some improvements to the current version which may correct this problem. How it was getting svg dimensional data was far more buggy in this past version. I'm, going to close this issue for now as I would need to see your SVG file to try to replicate the issue (and I figure I'm getting to this too late).

**Comment by jgcazares92** [comment]
Thanks for the update. I've gone ahead and installed the latest version. I'm running into a new issue though. When changing the import to `from pillow_vg import SVG` I get the module error: No module named 'pillow_svg'. Changing the import instead to `from PILSVG import SVG` seems to get around this problem but I then run into another issue. Namely, I get a ZeroDivisionError. I'm attaching the SVG file that I'm using for reference.
![plot1](https://user-images.githubusercontent.com/66054289/208218269-72396674-1207-42ee-ae75-50f822414a11.svg)
